mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('polls.urls')),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls_app'
urlpatterns = [
    # ex: /polls_app/
    url(r'^$', views.IndexView.as_view(), name="index"),
    # ex: /polls_app/5/
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls_app/5/results
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls_app/5/votes
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils import timezone


@python_2_unicode_compatible            # if you need to support python 2
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


@python_2_unicode_compatible            # if you need to support python 2
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class VoterDetail(models.Model):
    voter_id = models.CharField(max_length=20)
    voted = models.BooleanField(default=False)

    def __str__(self):
        return self.voter_id

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Question, Choice, VoterDetail


class IndexView(generic.ListView):
    template_name = 'polls_app/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls_app/detail.html'

    def get_queryset(self):
        """
        Exclude any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls_app/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls_app/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls_app:results', args=(question.id,)))

templates/base/base.html
{% load staticfiles %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Polls {% endblock %}</title>
    <link href="https://fonts.googleapis.com/css?family=Oswald" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/materialize.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

<div class="container">
    <div class="row">
        <div class="col l12 m9 s12">
            <div class="row">
                <div class="card blue lighten-5">
                    <div class="card-content center-block">
                        <span class="card-title center">Voting System</span>
                        <p class="left">
                            {% block content %}

                            {% endblock %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
<script src="{% static 'js/materialize.min.js' %}"></script>
</body>
</html>

templates/polls_app/detail.html
{% extends 'base/base.html' %}

{% block content %}
    <h5>{{ question.question_text }}</h5>

    {% if error_message %} <p class="red-text"><strong> {{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'polls_app:vote' question.id %}" method="post">
        {% csrf_token %}
        {% for choice in question.choice_set.all %}
            <p>
                <label>
                    <input type="radio" id="choice{{ forloop.counter }}" name="choice" value="{{ choice.id }}"/>
                    <span>{{ choice.choice_text }}</span>
                </label>
            </p>
        {% endfor %}
        <br>
        <input class="btn white black-text z-depth-1-half" type="submit" value="Vote"/>
    </form>

    <br>
    <div class="card-action">
        <a class="deep-purple-text" href="{% url "polls_app:index" %}">GOTO QUESTIONS PAGE</a>
    </div>
{% endblock %}

templates/polls_app/index.html
{% extends 'base/base.html' %}

{% block content %}
{% if latest_question_list %}
<ul style="list-style-type: circle !important;">
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls_app:detail' question.id %}" class="large-text">{{ question.question_text }}</a></li>
    {% endfor %}
</ul>
{% else %}
<h3>No polls are available.</h3>
{% endif %}
{% endblock %}

templates/polls_app/results.html
{% extends 'base/base.html' %}

{% block content %}
    <h4>{{ question.question_text }}</h4>

    <table class="striped">
        {% for choice in question.choice_set.all %}
            <tr>
                <td>{{ choice.choice_text }}</td>
                <td>{{ choice.votes }} vote{{ choice.votes|pluralize }}</td>
            </tr>
        {% endfor %}
    </table>
    <a href="{% url 'polls_app:detail' question.id %}">Vote again?</a>
{% endblock %}